version: "3.9"
services:
  mysql-container:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - app-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - app-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
    depends_on:
      - zookeeper
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  frontend:
    build: ./consultacredito-frontend
    container_name: consultacredito-frontend
    ports:
      - "4040:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./consultacredito-backend
    container_name: consultacredito-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_URL=kafka:9092
    networks:
      - app-network

networks:
  app-network:
    driver: host
