spring:
  application:
    name: consultacredito
  port: 8080
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_URL}
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
